name: Teardown

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    runs-on: [self-hosted, linux, X64]
    timeout-minutes: 5
    steps:
      - name: Run factory
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          cd ~/factory
          bash run.sh teardown "$PR_NUMBER"
